from __future__ import annotations

import unittest
from pathlib import Path

from src.adapters.model import ModelAdapter, ModelRequest, ModelResponse
from src.audits.gate4 import build_gate4_report
from src.budget.tokenizer import BudgetController, DeterministicRegexTokenizer
from src.domain.models import RepresentationArtifact, TargetEvidence, TargetVisible
from src.evidence_pack.builder import build_target_evidence_pack
from src.ingest.target import normalize_target_record
from src.writer.config import WRITER_CONDITIONS, load_writer_settings
from src.writer.writer import GenerationArtifact, Writer


ROOT = Path(__file__).resolve().parents[1]
WRITER_CONFIG = ROOT / "configs" / "writer.yaml"


def _settings():
    return load_writer_settings(WRITER_CONFIG)


def _tokenizer():
    return DeterministicRegexTokenizer()


def _pack():
    visible, evidence, _ = normalize_target_record(
        {
            "target_id": "ncphysics_test_001",
            "title": "Synthetic Physics Target",
            "abstract": "We study a deterministic oscillator under fixed parameters.",
            "non_intro_sections": {
                "Methods": "The fixture uses a fixed integration interval.",
                "Results": "The trajectory remains bounded.",
            },
            "reference_metadata": [{"title": "Ref", "year": 2024, "doi": "10.0/x"}],
            "gold_introduction": "Withheld gold 001.",
        }
    )
    return build_target_evidence_pack(visible, evidence, 8000, BudgetController(_tokenizer()))


def _representation(rep_type: str, content: str) -> RepresentationArtifact:
    return RepresentationArtifact(
        representation_id=f"rep_{rep_type}_test",
        type=rep_type,
        source_corpus_hash="a" * 64,
        compiler_model="test",
        compiler_prompt_version="test",
        compiler_input_tokens=0,
        compiler_output_tokens=0,
        compiler_calls=0,
        content=content,
        content_tokens=len(_tokenizer().encode(content)),
        content_hash=rep_type * 64,
    )


class _EchoAdapter(ModelAdapter):
    model_name = "echo"

    def generate(self, request: ModelRequest) -> ModelResponse:
        return ModelResponse(
            text="Introduction generated by the model path.",
            input_tokens=100,
            output_tokens=20,
            latency_ms=15,
            metadata={},
        )


class Stage4WriterTests(unittest.TestCase):
    def setUp(self) -> None:
        self.settings = _settings()
        self.tokenizer = _tokenizer()
        self.writer = Writer(self.settings, self.tokenizer, adapter=None)
        self.pack = _pack()
        self.representations = {
            "raw": _representation("raw", "Raw exemplar introduction text."),
            "summary": _representation("summary", "A compressed corpus summary."),
            "guideline": _representation("guideline", "Guideline: open with a problem."),
            "experience": _representation(
                "experience",
                '[{"experience_id": "exp_x", "tier": "stable_core", '
                '"observed_pattern": "p", "strategy": "State the claim directly.", '
                '"applicable_when": "w", "evidence": []}]',
            ),
        }

    def _run_all_conditions(self):
        artifacts: dict[str, GenerationArtifact] = {}
        for condition in WRITER_CONDITIONS:
            artifacts[condition] = self.writer.generate(
                self.pack, condition, self.representations.get(condition)
            )
        return artifacts

    def test_all_five_conditions_run(self) -> None:
        artifacts = self._run_all_conditions()
        self.assertEqual(set(artifacts), set(WRITER_CONDITIONS))
        for condition, artifact in artifacts.items():
            self.assertEqual(artifact.target_id, "ncphysics_test_001")
            self.assertEqual(artifact.condition, condition)
            self.assertTrue(artifact.text.strip())

    def test_evidence_hash_identical_across_conditions(self) -> None:
        artifacts = self._run_all_conditions()
        hashes = {artifact.target_evidence_hash for artifact in artifacts.values()}
        self.assertEqual(len(hashes), 1)

    def test_prompt_template_and_base_hashes_identical(self) -> None:
        artifacts = self._run_all_conditions()
        self.assertEqual(len({a.prompt_template_hash for a in artifacts.values()}), 1)
        self.assertEqual(len({a.base_prompt_hash for a in artifacts.values()}), 1)

    def test_only_representation_hash_differs(self) -> None:
        artifacts = self._run_all_conditions()
        self.assertIsNone(artifacts["evidence_only"].representation_hash)
        self.assertTrue(
            all(
                artifacts[condition].representation_hash is not None
                for condition in ("raw", "summary", "guideline", "experience")
            )
        )
        self.assertEqual(
            len({a.representation_hash for a in artifacts.values()}), len(WRITER_CONDITIONS)
        )
        self.assertEqual(len({a.writer_prompt_hash for a in artifacts.values()}), len(WRITER_CONDITIONS))

    def test_evidence_only_rejects_representation(self) -> None:
        with self.assertRaises(ValueError):
            self.writer.generate(self.pack, "evidence_only", self.representations["raw"])

    def test_writer_is_deterministic(self) -> None:
        first = self._run_all_conditions()
        second = self._run_all_conditions()
        for condition in WRITER_CONDITIONS:
            self.assertEqual(first[condition].generation_id, second[condition].generation_id)
            self.assertEqual(first[condition].text, second[condition].text)

    def test_model_path_works_and_records_costs(self) -> None:
        writer = Writer(self.settings, self.tokenizer, adapter=_EchoAdapter())
        artifact = writer.generate(self.pack, "guideline", self.representations["guideline"])
        self.assertEqual(artifact.writer_model, "echo")
        self.assertGreater(artifact.input_tokens, 0)
        self.assertGreater(artifact.output_tokens, 0)
        self.assertEqual(artifact.latency_ms, 15)
        self.assertEqual(artifact.text, "Introduction generated by the model path.")

    def test_gate4_report_passes(self) -> None:
        artifacts = self._run_all_conditions()
        costs = {
            condition: {
                "logged": True,
                "input_tokens": artifact.input_tokens,
                "output_tokens": artifact.output_tokens,
            }
            for condition, artifact in artifacts.items()
        }
        report = build_gate4_report(list(artifacts.values()), costs)
        self.assertTrue(report["passed"], report["checks"])
        self.assertEqual(report["target_id"], "ncphysics_test_001")


if __name__ == "__main__":
    unittest.main()
